// Products
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCTS_BY_NAME = 'GET_PRODUCTS_BY_NAME';
export const GET_PRODUCTS_BY_ID = 'GET_BY_ID';
export const CREATE_NEW_PRODUCT = 'CREATE_NEW_PRODUCT';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const GET_DELETED_PRODUCTS = 'GET_DELETED_PRODUCTS';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const RESTORE_PRODUCT = 'RESTORE_PRODUCT';

// LocalStorage
export const LOCAL_STORAGE = 'LOCAL_STORAGE';


// Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const FINISH_PURCHASE = 'FINISH_PURCHASE';


// Admin
export const REGISTER_ADMIN = 'REGISTER_NEW_ADMIN';


// Users
export const GET_ALL_USERS = 'GET_ALL_USERS';

export const REGISTER_USER = 'REGISTER_NEW_USER';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';

export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

export const POST_USER_REQUEST = 'POST_USER_REQUEST';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_FAILURE = 'POST_USER_FAILURE';

export const SEND_TOKEN_GOOGLE_REQUEST = 'SEND_TOKEN_GOOGLE_REQUEST';
export const SEND_TOKEN_GOOGLE_SUCCESS = 'SEND_TOKEN_GOOGLE_SUCCESS';
export const SEND_TOKEN_GOOGLE_FAILURE = 'SEND_TOKEN_GOOGLE_FAILURE';

export const CLEAR_DATA = 'CLEAR_DATA';

export const POST_MESSAGE_REQUEST = 'POST_MESSAGE_REQUEST';
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS';
export const POST_MESSAGE_FAILURE = 'POST_MESSAGE_FAILURE';

export const GET_USERDATA_REQUEST = 'GET_USERDATA_REQUEST';
export const GET_USERDATA_SUCCESS = 'GET_USERDATA_SUCCESS';
export const GET_USERDATA_FAILURE = 'GET_USERDATA_FAILURE';

export const PUT_USERDATA_REQUEST = 'PUT_USERDATA_REQUEST';
export const PUT_USERDATA_SUCCESS = 'PUT_USERDATA_SUCCESS';
export const PUT_USERDATA_FAILURE = 'PUT_USERDATA_FAILURE';

export const DELETE_USER = 'DELETE_USER';
export const GET_ALL_USERS_DELETED = 'GET_ALL_USERS_DELETED';
export const RESTORE_USER = 'RESTORE_USER';

export const GET_USER_PURCHASES_REQUEST = 'GET_USER_PURCHASES_REQUEST';
export const GET_USER_PURCHASES_SUCCESS = 'GET_USER_PURCHASES_SUCCESS';
export const GET_USER_PURCHASES_FAILURE = 'GET_USER_PURCHASES_FAILURE';

export const GET_ADMIN_PRODUCTS_REQUEST = 'GET_ADMIN_PRODUCTS_REQUEST';
export const GET_ADMIN_PRODUCTS_SUCCESS = 'GET_ADMIN_PRODUCTS_SUCCESS';
export const GET_ADMIN_PRODUCTS_FAILURE = 'GET_ADMIN_PRODUCTS_FAILURE';

export const GET_USER_PRODUCTS_REQUEST = 'GET_USER_PRODUCTS_REQUEST';
export const GET_USER_PRODUCTS_SUCCESS = 'GET_USER_PRODUCTS_SUCCESS';
export const GET_USER_PRODUCTS_FAILURE = 'GET_USER_PRODUCTS_FAILURE';

// Reviews
export const CREATE_REVIEW = 'CREATE_REVIEW';


//Pagination
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";


//Presentacion 
export const SET_FILTERS = "SET_FILTERS";