// Products
export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';

export const GET_PRODUCTS_BY_NAME_REQUEST = 'GET_PRODUCTS_BY_NAME_REQUEST';
export const GET_PRODUCTS_BY_NAME_SUCCESS = 'GET_PRODUCTS_BY_NAME_SUCCESS';
export const GET_PRODUCTS_BY_NAME_FAILURE = 'GET_PRODUCTS_BY_NAME_FAILURE';

export const GET_DETAIL_PRODUCT_REQUEST = 'GET_DETAIL_PRODUCT_REQUEST';
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS';
export const GET_DETAIL_PRODUCT_FAILURE = 'GET_DETAIL_PRODUCT_FAILURE';

export const GET_CATEGORIES = 'GET_CATEGORIES';


// Users
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';

export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE';

export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

export const POST_USER_REQUEST = 'POST_USER_REQUEST';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_FAILURE = 'POST_USER_FAILURE';

export const SEND_TOKEN_GOOGLE_REQUEST = 'SEND_TOKEN_GOOGLE_REQUEST';
export const SEND_TOKEN_GOOGLE_SUCCESS = 'SEND_TOKEN_GOOGLE_SUCCESS';
export const SEND_TOKEN_GOOGLE_FAILURE = 'SEND_TOKEN_GOOGLE_FAILURE';

export const GET_USERDATA_REQUEST = 'GET_USERDATA_REQUEST';
export const GET_USERDATA_SUCCESS = 'GET_USERDATA_SUCCESS';
export const GET_USERDATA_FAILURE = 'GET_USERDATA_FAILURE';

export const PUT_USERDATA_REQUEST = 'PUT_USERDATA_REQUEST';
export const PUT_USERDATA_SUCCESS = 'PUT_USERDATA_SUCCESS';
export const PUT_USERDATA_FAILURE = 'PUT_USERDATA_FAILURE';

export const GET_USER_PURCHASES_REQUEST = 'GET_USER_PURCHASES_REQUEST';
export const GET_USER_PURCHASES_SUCCESS = 'GET_USER_PURCHASES_SUCCESS';
export const GET_USER_PURCHASES_FAILURE = 'GET_USER_PURCHASES_FAILURE';

export const GET_ADMIN_PRODUCTS_REQUEST = 'GET_ADMIN_PRODUCTS_REQUEST';
export const GET_ADMIN_PRODUCTS_SUCCESS = 'GET_ADMIN_PRODUCTS_SUCCESS';
export const GET_ADMIN_PRODUCTS_FAILURE = 'GET_ADMIN_PRODUCTS_FAILURE';

export const GET_USER_PRODUCTS_REQUEST = 'GET_USER_PRODUCTS_REQUEST';
export const GET_USER_PRODUCTS_SUCCESS = 'GET_USER_PRODUCTS_SUCCESS';
export const GET_USER_PRODUCTS_FAILURE = 'GET_USER_PRODUCTS_FAILURE';

export const PUT_USER_ADMIN_REQUEST = 'PUT_USER_ADMIN_REQUEST';
export const PUT_USER_ADMIN_SUCCESS = 'PUT_USER_ADMIN_SUCCESS';
export const PUT_USER_ADMIN_FAILURE = 'PUT_USER_ADMIN_FAILURE';


// Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const FINISH_PURCHASE = 'FINISH_PURCHASE';


// Admin
export const DELETE_PRODUCTS_REQUEST = 'DELETE_PRODUCTS_REQUEST';
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCTS_FAILURE = 'DELETE_PRODUCTS_FAILURE';

export const UPDATE_PRODUCTS_REQUEST = 'UPDATE_PRODUCTS_REQUEST';
export const UPDATE_PRODUCTS_SUCCESS = 'UPDATE_PRODUCTS_SUCCESS';
export const UPDATE_PRODUCTS_FAILURE = 'UPDATE_PRODUCTS_FAILURE';

export const GET_DELETED_PRODUCTS = 'GET_DELETED_PRODUCTS';
export const RESTORE_PRODUCT = 'RESTORE_PRODUCT';

export const DELETE_USER = 'DELETE_USER';
export const GET_ALL_USERS_DELETED = 'GET_ALL_USERS_DELETED';
export const RESTORE_USER = 'RESTORE_USER';

// Reviews
export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE';

//Pagination
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";


//Presentacion 
export const SET_FILTERS = "SET_FILTERS";

//Message
export const POST_MESSAGE_REQUEST = 'POST_MESSAGE_REQUEST';
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS';
export const POST_MESSAGE_FAILURE = 'POST_MESSAGE_FAILURE';

export const CLEAR_MESSAGE_STATUS = 'CLEAR_MESSAGE_STATUS';
export const CLEAR_DATA = 'CLEAR_DATA';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';